=== ChapterSevenSeeds/ClickTrackGenerator/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "required": [
        "initial_offset_ms",
        "time_signatures",
        "title",
        "album",
        "artist"
    ],
    "properties": {
        "title": {
            "type": "string",
            "description": "The song title."
        },
        "album": {
            "type": "string",
            "description": "The song album."
        },
        "artist": {
            "type": "string",
            "description": "The song artist."
        },
        "initial_offset_ms": {
            "type": "integer",
            "description": "Offset the entire click track by this number of milliseconds when doing the overlay."
        },
        "time_signatures": {
            "type": "array",
            "items": {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "required": [
                    "numerator",
                    "denominator",
                    "measures",
                    "bpm"
                ],
                "properties": {
                    "numerator": {
                        "type": "integer",
                        "description": "The time signature numerator."
                    },
                    "denominator": {
                        "type": "integer",
                        "description": "The time siganture denominator."
                    },
                    "sub_beat_multiplier": {
                        "type": "integer",
                        "description": "Play a sub-beat click every nth numerator click (e.g. to give 12/8 a 4/4 division)."
                    },
                    "measures": {
                        "type": "integer",
                        "description": "The number of measures to play this time signature."
                    },
                    "bpm": {
                        "type": "number",
                        "description": "The number of ticks of the numerator per minute."
                    },
                    "offset": {
                        "type": "integer",
                        "description": "Offset this time signature by this number of milliseconds."
                    },
                    "sub_beats_as_upbeats": {
                        "type": "boolean",
                        "description": "If sub_beat_multiplier is specified, setting this to true will will treat the subbeats as upbeats, skipping the actual upbeats."
                    }
                }
            }
        }
    }
}

=== ChapterSevenSeeds/ClickTrackGenerator/Sempiternal Beings.json
{
    "title": "Sempiternal Beings",
    "album": "Fauna",
    "artist": "Haken",
    "time_signatures": [
        {
            "numerator": 7,
            "denominator": 8,
            "measures": 36,
            "bpm": 260
        },
        {
            "numerator": 13,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 47,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 13,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 47,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 13,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 16,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 31,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 13,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 47,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 15,
            "denominator": 16,
            "measures": 4,
            "bpm": 520
        },
        {
            "numerator": 7,
            "denominator": 8,
            "measures": 24,
            "bpm": 260
        },
        {
            "numerator": 13,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 19,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 13,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 19,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 13,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 19,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 13,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 19,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 15,
            "denominator": 16,
            "measures": 16,
            "bpm": 520
        },
        {
            "numerator": 8,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 6,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 10,
            "denominator": 16,
            "measures": 2,
            "bpm": 520
        },
        {
            "numerator": 6,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 6,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 10,
            "denominator": 16,
            "measures": 2,
            "bpm": 520
        },
        {
            "numerator": 6,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 6,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 10,
            "denominator": 16,
            "measures": 2,
            "bpm": 520
        },
        {
            "numerator": 6,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        },
        {
            "numerator": 6,
            "denominator": 16,
            "measures": 1,
            "bpm": 520
        }
    ],
    "initial_offset_ms": 200
}

=== ChapterSevenSeeds/ClickTrackGenerator/Atlas Stone.json
{
    "title": "Atlas Stone",
    "album": "The Mountain",
    "artist": "Haken",
    "time_signatures": [
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 74,
            "bpm": 420
        },
        {
            "numerator": 6,
            "denominator": 4,
            "measures": 8,
            "bpm": 105
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 17,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 13,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 16,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 32,
            "bpm": 420
        },
        {
            "numerator": 6,
            "denominator": 4,
            "measures": 8,
            "bpm": 105,
            "offset": 15
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 3,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 3,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 3,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 3,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 3,
            "bpm": 420
        },
        {
            "numerator": 10,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 18,
            "bpm": 420,
            "offset": 15
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 9,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 9,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 9,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 9,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 16,
            "bpm": 420,
            "offset": 15
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 9,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 9,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 9,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 9,
            "denominator": 8,
            "measures": 1,
            "bpm": 420
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 16,
            "bpm": 420,
            "offset": 10
        },
        {
            "numerator": 6,
            "denominator": 4,
            "measures": 8,
            "bpm": 105
        },
        {
            "numerator": 11,
            "denominator": 8,
            "measures": 3,
            "bpm": 420
        }
    ],
    "initial_offset_ms": -40
}
